### ISSUE TITLE
Why am I getting “unexpected end of file”?

### ISSUE THREAD

**Issue by jt0dd** [kpanuragh/zlib#3]
I'm using the unzipper Node.js package and it was working fine, processing through my files, when suddenly for seemingly no reason, I got this error:

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Emitted 'error' event on Parse instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

The error gets thrown every time this particular file is processed, others seem to work fine, but I can't think of what's different about this one. Other unzipper programs unzip the file just fine.

code:

```
console.log("unzipping", zipPath) // <-- error triggers after this log
fs.createReadStream(zipPath)
    .pipe(unzipper.Parse())
    .on('entry', function(entry) {
      entry.pipe(fs.createWriteStream(csvPath)).on('finish', () => {
        console.log("done unzipping", zipPath)
        fd = fs.openSync(csvPath, "r+")
        initializeFile()
      })
    })
}
```

**Comment by kpanuragh** [comment]
Can please send the example zip file file you processing ...?

**Comment by jt0dd** [comment]
I can't for legal reasons. It was 1GB+, maybe upwards of 7GB, I dont recall exactly but I think the smaller files didnt cause an error.

**Comment by kpanuragh** [comment]
I think its because of the file size, actually, this project is built for the browser environment so the project only works on the limited size of the file, If you want to process a large file you need to use Zlib nodejs core package  or you can process the file large file by reading small chunks and process the small chunks
